import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  bgDecorWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  sparkle: {
    position: "absolute",
    borderRadius: 9999,
  },
  panel: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 24,
    padding: 30,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    shadowColor: "#00FFFF",
    shadowOpacity: 0.2,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 6 },
    backdropFilter: "blur(12px)",
  },
  backBtn: {
    position: "absolute",
    top: 50,
    left: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  backText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  title: {
    fontSize: 34,
    color: "#00E0FF",
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 12,
    textShadowColor: "rgba(0,255,255,0.7)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
    letterSpacing: 1,
  },
  instruction: {
    fontSize: 18,
    color: "#DDD",
    textAlign: "center",
    marginBottom: 25,
  },
  reelsRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 20,
  },
  reelWindow: {
    backgroundColor: "#010A1A",
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#00E0FF",
    shadowColor: "#00E0FF",
    shadowOpacity: 0.4,
    shadowRadius: 8,
    marginHorizontal: 6,
    position: "relative",
  },
  reelGrad: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  digitCell: {
    justifyContent: "center",
    alignItems: "center",
  },
  middleDigitCell: {
    justifyContent: "center",
    alignItems: "center",
  },
  digitText: {
    color: "#00FFFF",
    fontWeight: "800",
    textShadowColor: "rgba(0,255,255,0.7)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  reelSep: {
    width: 24,
  },
  progressWrap: {
    alignItems: "center",
    marginBottom: 20,
  },
  progressFill: {
    height: 6,
    width: "100%",
    backgroundColor: "#00E0FF",
    borderRadius: 3,
    transformOrigin: "left",
    marginBottom: 16,
  },
  neonBtn: {
    alignSelf: "center",
  },
  winningRow: {
    alignItems: "center",
    marginTop: 20,
  },
  winningLabel: {
    fontSize: 20,
    color: "#fff",
    fontWeight: "bold",
    marginBottom: 8,
  },
  winningNumbers: {
    flexDirection: "row",
    justifyContent: "center",
  },
  winningNumber: {
    fontSize: 36,
    color: "#00E0FF",
    fontWeight: "900",
    marginHorizontal: 10,
    paddingVertical: 8,
    paddingHorizontal: 18,
    backgroundColor: "rgba(0,224,255,0.15)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,224,255,0.4)",
    textShadowColor: "rgba(0,255,255,0.6)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  winText: {
    color: "#FFD700",
    fontSize: 20,
    marginTop: 15,
    fontWeight: "bold",
    textShadowColor: "rgba(255,215,0,0.8)",
    textShadowRadius: 8,
  },
});
